<a href="https://colab.research.google.com/github/gopalbala/pytorch-workouts/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
print(torch.__version__)

2.6.0+cu124


In [3]:
# scalar
scalar = torch.tensor(7)

In [4]:
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
#vector
vector = torch.tensor([7,7])

In [8]:
vector

tensor([7, 7])

In [9]:
vector.ndim
vector.shape

torch.Size([2])

In [10]:
matrix = torch.tensor([[1,1,1],[2,2,2],[3,3,3]])

In [11]:
matrix

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [12]:
matrix.ndim

2

In [13]:
matrix.shape

torch.Size([3, 3])

In [14]:
tensor = torch.tensor([[[1,2,3],[3,4,5],[6,7,8]]])

In [15]:
tensor

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]])

In [16]:
tensor.shape

torch.Size([1, 3, 3])

In [17]:
tensor.ndim

3

In [18]:
tensor[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

In [19]:
tensor = torch.tensor([[
      [1,2,3],[3,4,5],[6,7,8]]
                       ,[[10,11,12],[13,14,15],[16,17,18]]])

In [20]:
tensor.shape

torch.Size([2, 3, 3])

In [21]:
tensor[1]

tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

In [22]:
rand_tensor = torch.rand(3,4)

In [23]:
rand_tensor

tensor([[0.9482, 0.4670, 0.4091, 0.0388],
        [0.0693, 0.2306, 0.9723, 0.8066],
        [0.7535, 0.4620, 0.4319, 0.9840]])

In [24]:
rand_tensor.ndim

2

In [25]:
rand_tensor = torch.rand(3, 3,4)

In [26]:
rand_tensor.ndim

3

In [27]:
rand_tensor = torch.rand(3,10,3,4)

In [28]:
rand_tensor.ndim

4

In [29]:
zero_tens = torch.zeros(3,3,4)

In [30]:
one_tens = torch.ones(3,3,4)

In [31]:
zero_tens.dtype

torch.float32

In [34]:
atensor = torch.arange(0,10)

In [35]:
like_tensor = torch.zeros_like(atensor)
like_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])